[package]
name = "jimn"
version = "0.1.0"
authors = ["frederic wagner <frederic.wagner@imag.fr>"]

[[bin]]
name = "main"
doc = false

[dependencies]
rand = "0.3"
byteorder = "0.5.3"
argparse = "0.2.1"
ordered-float = "0.4.0"
